# DUTA testnet example configuration

# Network selection
testnet=1

# Data directory
datadir=/root/.duta/testnet

# Local admin RPC only
rpcbind=127.0.0.1
rpcport=18083

# Public mining HTTP listener
mining_bind=0.0.0.0:18085

# P2P bind
bind=0.0.0.0
